language: android

android:
  components:
    - tools
    - platform-tools
    - build-tools-28.0.3
    - build-tools-29.0.0
    - android-29

script:
    - |
      if [ -z "$TRAVIS_TAG" ]
      then
        BINTRAY_DRY_RUN=true
      else
        BINTRAY_DRY_RUN=false
      fi
      ./gradlew clean :ntpclock:build :ntpclock:bintrayUpload -PbintrayUser=$BINTRAY_USER -PbintrayKey=$BINTRAY_KEY -PdryRun=$BINTRAY_DRY_RUN
      ./gradlew clean :ntpclock-date:build :ntpclock-date:bintrayUpload -PbintrayUser=$BINTRAY_USER -PbintrayKey=$BINTRAY_KEY -PdryRun=$BINTRAY_DRY_RUN
      ./gradlew clean :ntpclock-calendar:build :ntpclock-calendar:bintrayUpload -PbintrayUser=$BINTRAY_USER -PbintrayKey=$BINTRAY_KEY -PdryRun=$BINTRAY_DRY_RUN
      ./gradlew clean :ntpclock-time:build :ntpclock-time:bintrayUpload -PbintrayUser=$BINTRAY_USER -PbintrayKey=$BINTRAY_KEY -PdryRun=$BINTRAY_DRY_RUN
      ./gradlew clean :ntpclock-threetenbp:build :ntpclock-threetenbp:bintrayUpload -PbintrayUser=$BINTRAY_USER -PbintrayKey=$BINTRAY_KEY -PdryRun=$BINTRAY_DRY_RUN
      ./gradlew clean :ntpclock-joda:build :ntpclock-joda:bintrayUpload -PbintrayUser=$BINTRAY_USER -PbintrayKey=$BINTRAY_KEY -PdryRun=$BINTRAY_DRY_RUN

#after_success:
#  - bash <(curl -s https://codecov.io/bash)

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache